

import datetime, time
from datetime import datetime, timedelta

import pyqtgraph


class TimeAxis(pyqtgraph.AxisItem):

    def __init__(self, sense_view, *args, **kwargs):
        pyqtgraph.AxisItem.__init__(self, *args, **kwargs)
        self.sense_view = sense_view


    def tickStrings(self, values, scale, spacing):
        strings = []

        for v in values:
            v = int(v)
            display_time = datetime.fromtimestamp(time.mktime(self.sense_view.start_time)) + timedelta(seconds=0)
            display_time += timedelta(seconds=v / self.sense_view.current_video_meta.fps)

            strings.append(str(display_time).split(' ')[-1])


        return strings


class TimeAxisForSakuraPlot(pyqtgraph.AxisItem):

    def __init__(self, sense_view, *args, **kwargs):
        pyqtgraph.AxisItem.__init__(self, *args, **kwargs)
        self.sense_view = sense_view


    def tickStrings(self, values, scale, spacing):
        strings = []

        for v in values:

            v = int(v / 2)
            display_time = datetime.fromtimestamp(time.mktime(self.sense_view.start_time)) + timedelta(seconds=0)
            display_time += timedelta(seconds=v / self.sense_view.current_video_meta.fps)

            if str(display_time)[-1] in ['5', '0']:
                strings.append(str(display_time).split(' ')[-1])
            else:
                strings.append('')

        return strings


# NWWWWWWWWWWWWWWWWWWWWWWWWWNK00kkKNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWOc,';kXWWWWWWWWWWWWWWWWWWWWWWWW
# WMMMMMMMMMWMWWMMMMMMWMMWMWWWX0O0NWWMMWWMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMOcc;..:xKWMMMMMMMMWWWWMMMMMMMMM
# WMMMMMMWMMMMMWWMMMMWMWWMMMMMWNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMWx:ll,...':ldxkkkkxkKWWWWWMMMMMM
# WMMMWWWMMMMWMMMMMMMMMNNWMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMWNWMMMKlldoc,...........cONMMNNWWWMMMM
# WMMWWWMMMMWMMMMMMMMMWXXWMMMMMMMMMMMMMMMMMMNNWMMMMMMMMMMMMMMMMMMNXWWKocdddddc,''.....c0WMMMMWXXNWWMMM
# WMWWWMMMMMMMMMMMMMMMWKKWMMMMMMMMMMMMMMMMMWKKWMMMMMMMMMMMMMMMMMMWXOxllodddodl;'.....dWMMMMMMMWXKKXNWM
# WWWWWMMMMMMMMMMMMMMMNkOMMMMMMMMMMMMMMMMMMNkkNMMMMMMMMMMMMMMMMMNOdcclllllcccc;'....oWMMMMMMMMMWX000XW
# NWWMMMMMMMMMMMMMMMMW0oOWMMMMMMMMMMMMMMMMMNkdKWMMMMMMMMMMMMMMWXkdoolc:::cloool;...,0MMMMMMMMMMMWK000X
# NMMMMMMMMMMMMMMMMMMKkdkNMMMMMMMMMMMMMMMMMNOdkKWMMWNNXXXXXXNNNNWWWWX0Oxodkdllol,..cNMMMMMMMMMMMMNK00K
# NMMMMMMMMMMMMMMMMMNOkkxKMMMMMMMMMMMMMMMMMNOk0O0KKKKKKKXXXNNNNNNWWWNXKXO0WN0xol;..lWMMMMMMMMMMMMWXKK0
# NMMMMMMMMMMMMMMMMW0OXKxOWMMMMMMMMMMMMMMMMWOkXKkx0NMMMMMMMMMMMMMMMMWNKK0OXNWWX0d:'lXWMMMMMMMMMWN0Oxxx
# NMMMMMMMMMMMMMMMMXk0NNOxOKKXNWMMMMMMMMMMMM0kXNXK0KKKXNMMMMMMMMMMMMMWX00O0KXNWWWN0000000KXNNX0OO000kk
# NMMMMMMMMMMMMWWMNOOKK00kdk0KNWMMMMMMMMMMMMKkKNNWWNNXKKKKXNWMMMMMMMMMN0O0K00KXXNWWWWWXK0OOxdxOXWWX0XN
# NMMMMMMMMMMMWNWW0xOKKXNX0kOXWMMMMMMMMMMMMMNO0WWWWWWWWWXK0000KXNNWWWMNK0OXN0OO00KKXNWWWWWKk0NWWN0OXWW
# NMMMMMMMMMMMWNNKkONNNNNNNXkx0NWMMMMMMMMMMMW0ONWWWWWWWWWWWNNKK00OOO0KKKK0ONWNKOxkOO0KKXX0OXWWWXkkXWWX
# NMMMMMMMMMMMWXXOkXNNWWWWWWN0xkKWMMMMMMMMMMMN0XWWWWWWWWWWWWWWWWNXK0OOkxxxdOWMMWKkxxkOOkkdxXWWWXxONWWK
# NMMMMMMMMMMMWX0xONWWWWWNNWWNKkxkKWMMMMMMMMMMX0NWWWWWWWWWWWWWWWWWWWWWNX0OxxKMMMMWXkdddxkxodkKNN0xKNNX
# NMMMMMMMMMMMWKxdKWWWWWWXO0XNXKOxoxKNNNMMMMMMWKKNWWWWWWWWWWWWWWWKXWWWWWK0XOONMMMMMWN0xdodxxddxk0Ok0XX
# NWWMMMMMMMMMNOoxKK00KOdl'.':codkOO0KK00XWMMMMWKKWWWWWWNNNNXXNWk:dKKXKdckNXOKMMMMMMMWNKkdoodxxdoddxk0
# NNWMMMMMMMMMXxokXKd;.. ..     .:dOXXXKkxO0KNWMWXKNWWWWNK00K0d:. ..... ,kKX00WMMMMMWWWNXKOxoodkkxdooo
# KXWMMMMMMMMMKolkKOc. .:c.     .;xKKNWNXKOkO0KKXXKKXNWWWNKkl,',:ccccc:;ckKX0OXWX000KKK0K0Okkdx000KKOk
# 0XWMMMMMMMMW0llkkc..,oko,..;oo;.:KWWWWWWNXXNWNNXXXKXNWWNOoxOKNNNNNNNNXXXNN0xOkk0XNWWWWNNNNNNNNNNNNNX
# 0NMMMMMMMMMWOcoOX0:.lOXKo,'xWW0,.dWWWWWWWWWWWWWWWWWWWWWNNNWWWNNNNNNNNNNNNNOdxkk00KKKK000OOOO00KKKXXX
# 0NMMMMMMMMMNkclOXNOcoKWk'..:OXk;'oNWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNXOoONK00Okkkxxxxxxxxxxxxkkx
# 0NMMMMMMMMWKxolo0NNXKXWXc..,:llclOWWWWWWWNXNWWWWWWWWWWWWWWWWWNNNNNNNNNNNNXkokNMMMMMMMMMWWNNK0000000O
# 0WMMMMMMMMN0xdkddOXNNNWWXd:;clllkNWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNN0o:dXMMMMMMMMMMMMMNK000000O
# 0WMMMMMMMWX0doxkxdOXNNNNNNKkxkO0NWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNXxodxXMMMMMMMMMMMMMNK0000000
# KWMMMMMMMNK0xdddxxokXNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWNXXKXWWWWNNWWNNNNNNNOoxkkNMMMMMMMMMMMMWNKK000000
# KMMMMMMMWNK0kOOxdddoxXNNNNNNNNNNWWWWWWWWWWWWWWWWWNXKkkkkKWWWWNNNNNNNNNXkok0kOWMMMMMMMMMMMMNXK0000000
# XMMMMMMMWNKOOO00kddolkXNNNNNNNNNWWWWWWWNXXNNNNNNX0kO00KNWWNWWWNNNNNNNKxdk0OkKMMMMMMMMMMMMWXK0O000000
# XMMWWMMWNX0O0O000OkdolkXNNNNNNNWWWWWWWWNXKXXXNXXXXNNWWWNWWWWWWNNNNNXOxxO00kONMMMMMMMMMMMWNK0O0K00000
# XMWNWMMWWX000OO0O0000kdxKNNNNWWWWWWWWWWWWWWWWWNWNNNWWWWNNWWNNNNNNXOxxO000OkXMMMMMMMMMMMMNXKOO0KK0000
# XMNXWMMWWK00OO0000OO00OxdkKNNNNNWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNKkxxO0000OkKWMMMMMMMMMMMNXK0O0KKK00K0
# NNKXWMMMNK0OO00000OO0000OxxkOKNNWWWWWWWNWWWWWNWWWWWWWNNNNNNNX0xloO00000OkKWWWWMMMMMMMMNXK0O0KKKKKKK0
# NX0XWMMWX000000000OOOO00000OkkOO00KNNNNNNNNNNNWWWWWWNNNXXK0xololokkkkOkkKNNNWMMMMMMMWNXKOxOKKKKKKKK0
# KK0XWMMWK000000000OkkOOO0000000OkkkkkkO0KXNK0Oxdollcc:;;;,'..''..''',lOKKKNWMMMMMMMWXKKOdx0KKK0KKKK0
# 0K0XWMMNK0000000000kxkOkO00000000000Od:'';;,.......................;oxk0XWMMMMMMMWNXK0o,:x000KKKKKKK
# OK0KWMWXK000XNNXXK0OxxkxkOO0000Okdl:,'...........................',;,:kNMMMMMMMWNXK0d;. ,k0O0KKKKKKK
# k00KNMWXK00KXWWNNNK0OO0Oxddkxoc,.................................. .cKWMMMMMMWNXKOo,.   cOO0KKKKKKKK
# k0KKNMWXKKKKKXNNNNXKK0XNXOd:.. ...................................:kNMMMMMMWNX0xc.     'xOO0KKKKKKK0
# O0KKXWNXXNNXXXKXXXXXNNNNNk;.   ................................'ckNWMMMMWWX0xc'.      .lOO0KKKKKKKKK
# 00KKXWNKXNNNNNXKKKKXXXXKO:.    ...........................',:lkKWMMMWWX0xl;..         ;xO0KKKKKKKKKX
# X00KKNXKKKKKXKKXXXXXXXK00Oo,.             ...............';ldxkkkkxdl:'..            ;xO0KKKKKKKKKKN
# WN000KKK00000000KK0OKK00OOOOd;.         ..................................         .;dk0KKKKKKKKKKNM
# WMXd::::::::::;;;,..',,;;;;;;;'.         .:'.....'........'..''. .                 .',;:::::::::oKWM
# WMMKl'..........          .......... ..  .c',Ol.okc'.....'dxokl.....              .............c0WMM
# WMMMNOc'........                ,kkxxxkx''d;,KOo00l';xddx:'kNo,oxdOo.            ............:kNMMMM
# WMMMMMW0o;.......               oXclXlcXc;Xl,K0o0Ol,dO..xk.oK:l0,.oO'          ...........,lONMMMMMM
# WMMMMMMMWXOdc,.....             lK;:K:'kOO0;,0o.dOl';kxdkc.l0;,xxokl.       ..........,:okXWMMMMMMMM
# WMMMMMMMMMMMWKxl;'..            .;..;. .cl' .:' ,;.. 'll'  ';. .cl,        .......';lx0NMMMMMMMMMMMM
